### ISSUE TITLE
Can it use on ionic3 ?

### ISSUE THREAD

**Issue by uokivan** [AntonisKl/ionic-Incoming-Call-Recognition#1]
Dear AntonisKI
Thank you very much

Can I use it on ionic3?
It works on ionic3 ?

Thanks again

By Ivan

**Comment by uokivan** [comment]
Dear AntonisKl
Thank you very much

I know how to do it all right now,
and all the function is great.

Thank you so so much

By Ivan

**Comment by AntonisKl** [comment]
Hello,
I was about to answer to your first question now, but since you tested it on ionic v3 and it works then that's great! I would be happy to help if any other issue comes up in the future.
Thanks for the feedback.
